// <auto-generated />
namespace Svapas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AllModel19_02_20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllModel19_02_20));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191822521_AllModel19_02_20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
